### ISSUE TITLE
Summary - Feature Request

### ISSUE THREAD

**Issue by farishkash** [madhuinfos/bwa-u4-feature-request#1]
Overall met expectations.

Your feature request was concise, well articulated, and proposed a simple solution to improve the user experience.

There are two presentational issues I like to point out.

First, this is a technical document for your peers.  Make sure that you double check your spelling.

> In track component we need to add preview option to start playing the track. In track component add a method renderPreview method which will take previewUrl as an **arugment.**

Second, make sure you keep the argument name consistent across the document.  You started with previewUrl, but later on you wrote previewurl.

> Call the renderPreview() method in Track render method after renderAction, passing the **previewurl** as an argument. Read this preview url from props track object.

As a challenge for yourself, see if you can implement the features you documented.

**Comment by madhuinfos** [comment]
Hi Farishkash,

Thanks for the very quick feedback. 
I resolved the two issues mentioned and updated the document. Please check.
For jamming project i added the preview option and committed the code to the same repository.

Thanks!
